name: CD — Déploiement Firebase Hosting

on:
  workflow_run:
    workflows: ["CI — Analyse & Tests"]
    types:
      - completed

jobs:
  deploy:
    # Exécuter seulement si le CI a réussi
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    name: 🚀 Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: stable
          cache: true

      - name: Installer dépendances
        run: flutter pub get    

      - name:  Build Web app
        run: flutter build web --release

      - name: 🚀 Déployer sur Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: mts-web-92af8